### ISSUE TITLE
Code precheck errors

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-gradereport_gradeconfigwizard#15]
La validación de Moodle Plugins da algunos errores.

Code prechecks

phplint phpcs111 | 183 js0 | 87 css11 | 3 phpdoc27 | 0 savepoint thirdparty grunt1 | 1 shifter mustache0 | 11 gherkin130 | 0

Por favor, revisadlo con CodeChecker.

**Comment by jordiaubia** [comment]
Buenos días,

Revisamos y os avisamos cuando esté solucionado.

Muchas gracias,

Jordi

**Comment by jordiaubia** [comment]
Resuelto - https://github.com/UNIMOODLE/moodle-gradereport_gradeconfigwizard/pull/16
