### ISSUE TITLE
La versión de Moodle necesaria no existe

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-gradereport_gradeconfigwizard#26]
Buenas,

El plugin pide la versión miínima de Moodle 2024053000, y esta no existe. Lo he buscado en: https://moodledev.io/general/releases

Esto impide su instalación de 0.

Un saludo

**Comment by jordiaubia** [comment]
Hola Toni,

Si quieres instalar la versión anterior, que es compatible con 4.1, 4.2 i 4.2, puedes hacerlos desde esta branch: https://github.com/UNIMOODLE/moodle-gradereport_gradeconfigwizard/tree/MOODLE_401_STABLE

Actualmente la main es para versión 4.5, pero vamos a validar que es compatible con la versión 4.4 y, en caso de ser así, actualizamos el version.

Muchas gracias,
