### ISSUE TITLE
Error al establecer configuración de ponderaciones y notas de corte.

### ISSUE THREAD

**Issue by jmazcunanpentec** [UNIMOODLE/moodle-gradereport_gradeconfigwizard#28]
Buenas, 

<img width="360" alt="captura_error" src="https://github.com/user-attachments/assets/1932083c-1ed2-4f6d-9c92-75346ef066a8"> 

La parte superior de la imagen adjunta representa las condiciones de configuración contempladas. Se trata de una asignatura en la que el 70% de la nota proviene de las prácticas, siendo estas dos prácticas que son ponderadas al 50%.

El otro 30% de la nota corresponderá a la nota de los exámenes, siempre que esta sea como mínimo un En ese caso, se contemplará un 40% de nota por el examen Parcial y un 60% de nota por el examen final.

En la parte inferior de la imagen está la captura de la configuración propuesta trasladada al panel de configuración.

Al aplicar esto, se produce un error:

`Excepción - Argument 1 passed to gradereport_gradeconfigwizard\multiplegradebook::move_grade_item_to_category() must be of the type int, null given, called in [dirroot]\grade\report\gradeconfigwizard\classes\multiplegradebook.php on line 90`

Un saludo.

**Comment by jordiaubia** [comment]
Buenos días,

Intentamos reproducir el error y lo corregimos en la mayor brevedad posible.

Muchas gracias,

**Comment by tmas0** [comment]
Buenas,

¿Tenemos novedades al respecto?

Un saludo

**Comment by jordiaubia** [comment]
Buenos días Toni,

Disculpa la demora pero el técnico responsable no estuvo disponible algunas semanas.

Después de revisarlo hemos sido incapaces de reproducir el error que comentas.

**Caso 1.** Se reproduce la configuración tal como nos compartes y no se obtiene ningún error.

![C1_confi_inicial](https://github.com/user-attachments/assets/304bd618-045a-4f15-b8c7-b8f42387e4f9)
![C1_resultado_inicial](https://github.com/user-attachments/assets/52e3057e-b83d-43fa-b10f-11b12ae6b493)


**Caso 2.** El único error que conseguimos forzar es si añadimos nota de corte pero no especificamos ninguna actividad de recuperación (cosa que no vemos en tu ejemplo pero no sabemos al 100% si cuando lo probaste se olvidó este punto). En este caso es normal el error ya que la premisa de la nota de corte es que haya una actividad e recuperación. Igualmente, vamos a realizar una pequeña mejora para que no se posible guardar sin que se haya establecido dicha actividad.

![C2_confi_error](https://github.com/user-attachments/assets/1cab7066-be2b-431f-a491-a69edb58495e)
![C2_resultado_error](https://github.com/user-attachments/assets/a5205100-49b2-4885-8327-84fae7ccb9f4)


Así pues, en este sentido creemos que no hay un problema de código per se. La posible explicación que encontramos es que la información de los ítems se carga desde javascript y cabe la posibilidad de que se haya producido un error en el navegador que hubiera impedido el correcto funcionamiento o que el mismo esté configurado para que javascript no se ejecute. ¿Puedes revisar si se puede tratar de este problema?

También querríamos asegurarnos que la versión que tienes instalada es la más reciente.

Ya quedamos a la espera de tus comentarios.

Muchas gracias,
